### ISSUE TITLE
Add functionality to extract payload structure without decoding it

### ISSUE THREAD

**Issue by Wollac** [alloy-rs/rlp#17]
For certain use cases, the type of an RLP payload is not known in advance, but depends on its structure.

An example of this is the MPT node, which can be either a branch or a leaf node depending on the number of items in the list. Here, it would be helpful to have a function that extracts the payload structure without having to specify its type.

When implemented in the application, this adds quite a bit of error-prone boilerplate code (see for example here: [`decode` in `alloy-trie`](https://github.com/alloy-rs/trie/blob/262a84d7bed04b06f8579293b87708ad1bea3e2d/src/nodes/mod.rs#L55-L71)), and having it in the RLP library would be beneficial.

Such a function might look something like the following
```rust
enum Payload<'a> {
    String(&'a [u8]),
    List(Vec<&'a [u8]>),
}

fn decode_raw<'a>(buf: &mut &'a [u8]) -> Result<Payload<'a>>;
```

I can provide a PR with this feature, if this seems relevant for this crate.

**Comment by Rjected** [comment]
Yeah this would be nice
